# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nome')),
                ('emails', models.TextField(blank=True, verbose_name='Emails')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='Avatar URL')),
                ('position', models.TextField(blank=True, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
    ]
